### PR TITLE
Minor tweaks

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by mulkieran** [comment]
Thanks for your work on this! These are all very minor, but the last commit, which broadens the parameter type, would be a convenience.

**Comment by mulkieran** [comment]
I don't think that the error is my fault...

**Comment by mdaffin** [comment]
Thanks for this, the changes look good. That fail does not look like your fault, could be one of the dependencies no longer works with 1.7.0 I will have a look at it when I have a moment.

**Comment by mdaffin** [comment]
Looks like master is failing for the same reason.

**Comment by mdaffin** [comment]
Version 0.1.1 has now been published with these changes.

**Comment by mulkieran** [comment]
Thanks!

**Pull request merged**
